
export const FILTER_CMMDATA = 'FILTER_CMMDATA';
export const LOAD_CMMDATA_SUCCESS = 'LOAD_CMMDATA_SUCCESS';
export const LOAD_CMMDATA_EMPLOYEES_SUCCESS = 'LOAD_CMMDATA_EMPLOYEES_SUCCESS';
export const LOAD_CMMDATA_JOBS_SUCCESS = 'LOAD_CMMDATA_JOBS_SUCCESS';
export const LOAD_CMMDATA_SERVICES_SUCCESS = 'LOAD_CMMDATA_SERVICES_SUCCESS';
export const UNLOAD_CMMDATA_SUCCESS = 'UNLOAD_CMMDATA_SUCCESS';
export const UNLOAD_CMMDATA_EMPLOYEES_SUCCESS = 'UNLOAD_CMMDATA_EMPLOYEES_SUCCESS';
export const UNLOAD_CMMDATA_JOBS_SUCCESS = 'UNLOAD_CMMDATA_JOBS_SUCCESS';
export const UNLOAD_CMMDATA_SERVICES_SUCCESS = 'UNLOAD_CMMDATA_SERVICES_SUCCESS';
